---
hugo_env: &hugo_env
   BASE_BUCKET_URL: $BUCKET_URL

kind: pipeline
name: hugo-website
steps:
  - name: hugo-build
    image: peaceiris/hugo:v0.65.3-mod
    environment:
      <<: *hugo_env
    commands:
      - hugo --baseURL $BASE_BUCKET_URL

  - name: login-to-AWS
    image: amazon/aws-cli
    commands:
      - aws configure set aws_access_key_id $aws_access_key_id
      - aws configure set aws_secret_access_key $aws_secret_access_key
      - aws configure set aws_session_token $aws_session_token
      - aws configure set default.region $aws_region

  - name: deploy-to-s3
    image: amazon/aws-cli
    environment:
      <<: *hugo_env
    commands:
      - aws s3 sync ./public $BUCKET_URL --delete --exact-timestamps --acl public-read

trigger:
  branch:
    - main
  event:
    - push